specVersion: 0.2.0
name: subqlHelloWorld
version: 0.0.4
description: >-
  This SubQuery project can be use as a starting point for Moonbeam alpha
  network
repository: 'https://github.com/subquery/moonbeam-alpha-subql-starter'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://gateway.testnet.octopus.network/barnacle-evm/wj1hhcverunusc35jifki19otd4od1n5'
  genesisHash: '0xd0599a36a2fb1e958d74c51c439b63f5ee91b7c107940caec1ec78958c2d3422'
  dictionary: 'https://sz.api.subquery.network/sq/subquery/moonbase-alpha-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
