specVersion: 0.2.0
name: subqlHelloWorld
version: 0.0.4
description: >-
  This SubQuery project can be use as a starting point for Moonbeam alpha
  network
repository: 'https://github.com/subquery/moonbeam-alpha-subql-starter'
schema:
  file: ./schema.graphql
network:
  endpoint: 'ws://localhost:9944'
  genesisHash: '0x6ea1b9835ddf9b9a4e2cef4e84bc6ceb17a29157d3e63489e3e727ddb20fe560'
  dictionary: 'https://sz.api.subquery.network/sq/subquery/moonbase-alpha-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
